### ISSUE TITLE
Scalatra 2.6.0

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra#672]
This is an aggregation ticket of Scalatra 2.6.0 progress.

The main goal of Scalatra 2.6.x is to decrease future maintenance efforts and costs, since there are not enough active committers to maintain the existing huge codebase. To achieve this goal, we focus the followings in 2.6.0:

- Follow the Scala standards (e.g. Twirl instead of Scalate)
- Deprecate modules that are not used much or not maintained enough

## Overall

- [x] Upgrade libraries and Jetty #688
- [x] Remove all deprecated classes and methods #674 
- [x] Adopt Twirl as the default template engine (Update g8 template) https://github.com/scalatra/scalatra-sbt.g8/pull/74

## Modules

We have many modules in Scalatra, too many to be maintained by the current active committers. We wish to drop unimportant or outdated modules in the future, so we deprecate or merge some modules as follows in Scalatra 2.6.0:

- [x] Deprecate Swagger 1.x support and merge scalatra-swagger-ext with scalatra-swagger #681
- [x] Deprecate scalatra-commands and introduce [scalatra-forms](https://github.com/gitbucket/scalatra-forms) instead #679
- [x] Deprecate scalatra-spring #673
- [x] Drop scalatra-example because we have examples in scalatra-website-example by @magnolia-k
- [x] Drop scalatra-fileupload because it has been already deprecated since 2.1.0 #675
- [x] Merge request logging utility in scalatra-slf4j with core, and drop scalatra-slf4j #699

All deperecated features in 2.6.x will be dropped in 2.7.0 or 3.0.0.

## Documents

- [x] Create 2.6 guides and scaladoc https://github.com/scalatra/scalatra-website/issues/152 and #715
- [x] Create 2.6 examples https://github.com/scalatra/scalatra-website-examples/pull/46

## Others

- [x] Refactoring #729

**Comment by magnolia-k** [comment]
The template of the twirl version was also made possible

https://github.com/magnolia-k/scalatra-sbt.g8

**Comment by takezoe** [comment]
@magnolia-k Great! We have to update docs and dependencies in the template as well. Keep your template repository until 2.6.0 will be ready.

**Comment by jb08** [comment]
@takezoe, what's the best way to deprecate swagger 1.0? Use http status code `410 (Gone)`? I'd like to work on it. Is there an example you could send of something scalatra has deprecated?

**Comment by takezoe** [comment]
@jb08 In fact, it's difficult stuff. We should inform to developers that "You must move to Swagger 2.0 in the future." with keeping current behavior. I don't have clear idea yet, how about follows?

- Output WARN log if Swagger version 1.x is specified
- Add the deprecated annotation to methods which are not used in Swagger 2.0

**Comment by magnolia-k** [comment]
I'm thinking of doing the following tasks.

> Deprecate scalatra-commands and introduce scalatra-forms instead

**Comment by takezoe** [comment]
@magnolia-k Thanks. scalatra-forms would require some extra work before merging. I'm considering about it just now, so could you do "Deprecate scalatra-commands" as a separate pull request?

**Comment by salceson** [comment]
> ScalaTest instead of Specs2

Will Specs2 integration for writing tests be still maintained? I mean will I still be able to write tests with Scalatra with Specs2?

**Comment by magnolia-k** [comment]
At this time, support of specs 2 is never stopped immediately.
See Scalatra's Gitter for details.

https://gitter.im/scalatra/scalatra

**Comment by takezoe** [comment]
@magnolia-k Thanks! I updated the description of this issue to drop that part.

**Comment by takezoe** [comment]
Since unidoc is going to be published to the Maven central repository by #715, we can reference https://www.javadoc.io/ instead of hosting on the our web site.
