### ISSUE TITLE
[Draft] Scalatra 2.7.0

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra#765]
This is an aggregation ticket of Scalatra 2.7.0 progress.

The main goal of Scalatra 2.7.x is clean up codebase as same as 2.6.x, and we want to follow more modern technology like Servlet 4.0 or Swagger 3.0.

## scalatra-twirl

- [x] Twirl specific view helpers for scalatra-forms #767
- [ ] Add reverse routing support as same as scalatra-scalate #768

## scalatra-scalate

- [x] Scalate specific view helpers for scalatra-forms #766 
- [ ] Make useable with ScalatraFilter as well #769

## scalatra-forms

- [x] Move view helpers to scalatra-scalate and scalatra-twirl #766, #767
- [ ] Add value types for additional data types like date and datetime

## scalatra-json

- [ ] Add new JSON support based on modern JSON library (scalatra-json2?)
- [ ] Deprecate existing json4s based JSON support

## scalatra-swagger

- [x] Drop Swagger 1.x support #748
- [x] Merge scalatra-swagger-ext with scalatra-swagger
- [ ] Swagger 3.0 support #749
- [ ] Move to new JSON support mentioned above

## Documents

- Create 2.7 guides
  - [ ] Update JSON guides to use new JSON support
  - [ ] Update scalatra-form guide to use view helpers in scalatra-twirl and scalatra-scalate
  - [ ] Update Swagger guide to use Swagger 3.0
  - [ ] Update Twirl guide to use scalatra-twirl
  - [ ] Add server push guide
- Create 2.7 examples
  - [ ] Update JSON examples to use new JSON support
  - [ ] Update scalatra-form example to use scalatra-twirl
  - [ ] Add scalatra-form-scalate example
  - [ ] Update Swagger example to use Swagger 3.0
  - [ ] Add server push example

## Others

- [x] Drop scalatra-spring, scalatra-commands and all deprecated code in Scalatra 2.6 #748
- [x] Merge scalatra-cache-guava with scalatra-cache #748

**Comment by magnolia-k** [comment]
What kind of JSON library is applicable to "modern JSON library" here?

**Comment by takezoe** [comment]
@magnolia-k For example, play-json, spray-json or cirse which don't use runtime reflection. But first, it might have to be provided as optional module.

**Comment by magnolia-k** [comment]
@takezoe 
Although not all of this list has been erased yet, it has been two years since the release of Scalatra 2.6, and since Scala 2.13 and JDK 11 have been prepared, the idea of once releasing 2.7 is what I wonder
There is still something to be done such as support for the new JSON module and support for Swagger 3.0 (Open API), but in order to support it, it is necessary to consider a sufficient design, and it takes a considerable amount of time to release .

**Comment by magnolia-k** [comment]
First of all, isn't it better to make 2.7.0-M1 and make documents and sample code accordingly?

**Comment by takezoe** [comment]
Totally agree. It's time to proceed Scalatra 2.7. Let's make 2.7.0-M1.

**Comment by jnatten** [comment]
Any ETA for when a production ready build for 2.13 will be available? :)

**Comment by takezoe** [comment]
Scalatra 2.7.0 released. Remaining issues have been moved to 2.7.1.
